#!/usr/bin/env bash
# dds_setup.sh — generate a Fast DDS profile for THIS PC so it can see the
# Jetson's ROS topics in RViz without crossing DDS multicast or hitting the
# docker0 IP collision.
#
# The Jetson side is handled by dds_jetson.xml (static, always-on via dds_env.sh
# sourced by every container shell).  This script only runs on the PC.
#
# Usage (called by rviz_eyerobot.sh; can also be run standalone):
#   PC_PROFILE="$(./dds_setup.sh)"                   # default Jetson IP
#   PC_PROFILE="$(./dds_setup.sh 128.179.186.106)"   # explicit Jetson IP
#   export FASTRTPS_DEFAULT_PROFILES_FILE="$PC_PROFILE"
#
# Prints the generated profile path on stdout; progress messages go to stderr.
set -eo pipefail

JETSON_HOST="${JETSON_HOST:-${1:-128.179.186.106}}"

# Detect this PC's outbound interface and IP toward the Jetson.
PC_IP="$(ip route get "$JETSON_HOST" 2>/dev/null | grep -oP 'src \K[\d.]+' | head -1)"
PC_IFACE="$(ip route get "$JETSON_HOST" 2>/dev/null | grep -oP 'dev \K\S+' | head -1)"
if [ -z "$PC_IP" ] || [ -z "$PC_IFACE" ]; then
  echo "dds_setup: cannot determine this PC's route to $JETSON_HOST" >&2
  exit 1
fi

PC_PROFILE="${TMPDIR:-/tmp}/eyerobot_dds_pc.xml"

cat > "$PC_PROFILE" <<XML
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  Fast DDS PC-side profile for EyeRobot RViz — generated by dds_setup.sh.
  PC: ${PC_IP} (${PC_IFACE})   Jetson: ${JETSON_HOST}

  Restricts DDS to the PC's WiFi interface (excludes docker0 at 172.17.0.1)
  and adds the Jetson as a unicast initial peer (campus WiFi blocks multicast).
  The Jetson profile (dds_jetson.xml) lists only 127.0.0.1 as its peer; the PC
  initiates cross-machine discovery by probing the Jetson IP — the Jetson
  responds and both sides discover each other fully from that point.
-->
<dds xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
  <profiles>
    <transport_descriptors>
      <transport_descriptor>
        <transport_id>wifi_and_lo</transport_id>
        <type>UDPv4</type>
        <interfaceWhiteList>
          <address>${PC_IFACE}</address>
          <address>127.0.0.1</address>
        </interfaceWhiteList>
      </transport_descriptor>
    </transport_descriptors>

    <participant profile_name="default_participant" is_default_profile="true">
      <rtps>
        <useBuiltinTransports>false</useBuiltinTransports>
        <userTransports>
          <transport_id>wifi_and_lo</transport_id>
        </userTransports>
        <builtin>
          <discovery_config>
            <initialPeersList>
              <locator><udpv4><address>127.0.0.1</address></udpv4></locator>
              <locator><udpv4><address>${JETSON_HOST}</address></udpv4></locator>
            </initialPeersList>
            <max_initial_peers_range>32</max_initial_peers_range>
          </discovery_config>
        </builtin>
      </rtps>
    </participant>
  </profiles>
</dds>
XML

echo "dds_setup: PC=${PC_IP} (${PC_IFACE}) → Jetson=${JETSON_HOST} — profile: ${PC_PROFILE}" >&2
echo "$PC_PROFILE"
