#!/usr/bin/env bash
# dds_setup.sh — generate a Fast DDS profile for THIS PC so it can see the
# Jetson's ROS topics in RViz without hitting the docker0 IP collision.
#
# The Jetson side is handled by dds_jetson.xml (static, always-on via dds_env.sh
# sourced by every container shell).  This script only runs on the PC.
#
# Two modes:
#   Multicast mode (phone hotspot / home network — multicast not blocked):
#     ./dds_setup.sh                    # no arg → auto-detect WiFi iface
#   Unicast mode (campus WiFi — multicast blocked):
#     ./dds_setup.sh 128.179.186.106    # explicit Jetson IP → add as unicast peer
#     JETSON_HOST=1.2.3.4 ./dds_setup.sh
#
# In multicast mode the profile just excludes docker0 from the transport; DDS
# multicast discovery then finds the Jetson on its own.  In unicast mode a
# direct peer entry is added so discovery works even without multicast.
#
# Prints the generated profile path on stdout; progress messages go to stderr.
set -eo pipefail

JETSON_HOST="${JETSON_HOST:-${1:-}}"   # empty = multicast / hotspot mode

# --- Detect this PC's outbound WiFi interface ---
if [ -n "$JETSON_HOST" ] && ip route get "$JETSON_HOST" >/dev/null 2>&1; then
    # Unicast mode: use the interface the kernel would route toward the Jetson.
    PC_IP="$(ip route get "$JETSON_HOST" 2>/dev/null | grep -oP 'src \K[\d.]+' | head -1)"
    PC_IFACE="$(ip route get "$JETSON_HOST" 2>/dev/null | grep -oP 'dev \K\S+' | head -1)"
else
    # Multicast mode: pick the first non-docker, non-virtual interface.
    PC_IFACE="$(ip -o -4 addr show up scope global 2>/dev/null \
        | awk '$2 !~ /^(lo|docker0|br-|veth)/ { print $2; exit }')"
    if [ -z "$PC_IFACE" ]; then
        echo "dds_setup: no usable network interface found" >&2
        exit 1
    fi
    PC_IP="$(ip -4 addr show "$PC_IFACE" 2>/dev/null \
        | awk '/inet / { sub(/\/.*/, "", $2); print $2; exit }')"
fi

if [ -z "$PC_IP" ] || [ -z "$PC_IFACE" ]; then
    echo "dds_setup: cannot determine PC IP/interface" >&2
    exit 1
fi

# Optional unicast peer entry for the Jetson (only in campus-WiFi mode).
JETSON_PEER=""
[ -n "$JETSON_HOST" ] && \
    JETSON_PEER="<locator><udpv4><address>${JETSON_HOST}</address></udpv4></locator>"

PC_PROFILE="${TMPDIR:-/tmp}/eyerobot_dds_pc.xml"

cat > "$PC_PROFILE" <<XML
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  Fast DDS PC-side profile for EyeRobot RViz — generated by dds_setup.sh.
  PC: ${PC_IP} (${PC_IFACE})   Jetson: ${JETSON_HOST:-multicast}
-->
<dds xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
  <profiles>
    <transport_descriptors>
      <transport_descriptor>
        <transport_id>wifi_and_lo</transport_id>
        <type>UDPv4</type>
        <!-- Exclude docker0 (172.17.0.1 on both machines — causes packets to
             loop back to the local bridge instead of reaching the Jetson). -->
        <interfaceWhiteList>
          <address>${PC_IP}</address>
          <address>127.0.0.1</address>
        </interfaceWhiteList>
        <maxInitialPeersRange>32</maxInitialPeersRange>
      </transport_descriptor>
    </transport_descriptors>

    <participant profile_name="default_participant" is_default_profile="true">
      <rtps>
        <useBuiltinTransports>false</useBuiltinTransports>
        <userTransports>
          <transport_id>wifi_and_lo</transport_id>
        </userTransports>
        <builtin>
          <!-- 127.0.0.1 for local discovery; Jetson IP added in unicast/campus mode. -->
          <initialPeersList>
            <locator><udpv4><address>127.0.0.1</address></udpv4></locator>
            ${JETSON_PEER}
          </initialPeersList>
        </builtin>
      </rtps>
    </participant>
  </profiles>
</dds>
XML

echo "dds_setup: PC=${PC_IP} (${PC_IFACE}) Jetson=${JETSON_HOST:-multicast} → ${PC_PROFILE}" >&2
echo "$PC_PROFILE"
